// <auto-generated />
namespace ProyectoVehiculo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB_VEHICULO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_VEHICULO));
        
        string IMigrationMetadata.Id
        {
            get { return "201604150148112_DB_VEHICULO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
